In [38]:
import numpy as np

arr1 = np.array([1,2,3,4,5])

print(arr1)  
print(arr1[0])
print(arr1[2]) 

[1 2 3 4 5]
1
3


In [47]:
arr2 = np.array([[3,1,4],
              [4,11,5],
              [8,67,9]])
print(arr2.shape)
print('\n', arr2)

(3, 3)

 [[ 3  1  4]
 [ 4 11  5]
 [ 8 67  9]]


In [48]:

print(arr2[2, 1])
print(arr2[1, 0])
print(arr2[2, 2])

67
4
9


In [49]:
#slicing 2D array
print(arr2[1:,1:2])


[[11]
 [67]]


In [50]:
#negative slicing
arr2[-2:,0:1]

array([[4],
       [8]])

In [51]:
arr2[-2:,1:2]

array([[11],
       [67]])

In [ ]:
 #NEGATIVE SLICING IS POSSIBLE IN N-DIMENSIONAL ARRAY